# Site settings
description: "Paolo Almeida - Front-end Engineer & UX/UI Creative"
baseurl: ""
url: "http://paoloalmeida.com.br"

# User settings
username: "Paolo Almeida"
user_description: "Paolo Almeida | Front End Engineer / UX/UI Creative / SEO Specialist"
user_title: "Paolo Almeida | Front End Engineer / UX/UI Creative / SEO Specialist"
email: paolo.2frame@gmail.com
twitter_username: paolo_almeida
github_username:  paoloalmeida
gplus_username:  PaoloAlmeidaFrontend
disqus_username: paoloalmeida

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

