# Site settings
description: My personal site ;)
baseurl: ""
url: "http://paoloalmeida.com.br"

# User settings
username: Paolo Almeida
user_description: A Front End Engineer and UX/UI Designer
user_title: Front End Engineer
email: paolo.2frame@gmail.com
twitter_username: paolo_almeida
github_username:  paoloalmeida
gplus_username:  lorem_ipsum
disqus_username: paoloalmeida

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
